### PR TITLE
fixes 'kfctl Incorrect ksonnet OptionServer is specified when no platform is provided'

### LINKED ISSUE #2761: kfctl Incorrect ksonnet OptionServer is specified when no platform is provided
If you run 

```
kfctl init ~/kubeflow && \
cd kubeflow && \
kfctl generate all && \
kfctl apply all
```

you'll get the error 
```
ERRO[0000] (Will retry) Component metacontroller apply failed; Error: Attempting to deploy to environment 'default' at '127.0.0.1', but cannot locate a server at that address  filename="ksonnet/ksonnet.go:191"
```

### PR DESCRIPTION
**Pull request by kkasravi**
fixes #2761

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2763)

### CODE REVIEW

File: bootstrap/pkg/kfapp/ksonnet/ksonnet.go [hunk 1]
```diff
@@ -447,16 +447,18 @@ func (ksApp *ksApp) initKs() error {
 	}
 	ksApp.KsEnvName = KsEnvName
 	k8sSpec := ksApp.Spec.ServerVersion
+	host := "127.0.0.1"
 	if k8sSpec == "" {
-		k8sSpec = kftypes.GetServerVersion(kftypes.GetClientset(kftypes.GetConfig()))
```
Comment (kunmingg) [inline bootstrap/pkg/kfapp/ksonnet/ksonnet.go]: Shall we just throw exception on ```k8sSpec == ""```?
If we cache spec in kubeflow repo it should never be empty?
https://github.com/kubeflow/kubeflow/pull/2765/files
