### PR TITLE
Fix #285 and make few tweaks to notebook Dockerfile

### LINKED ISSUE #285: How to add persistent volume in jupyter_spawner.py file ?
Hi,

I have followed these steps https://github.com/kubeflow/kubeflow/blob/master/user_guide.md to deploy kubeflow.
I'm able to see Jupyter notebook interface after logging into the jupyter hub.
now to add persistent volume if I follow the steps mentioned here https://github.com/kubeflow/kubeflow/pull/22/files/48ffe99d30eb31abc4d54c4553483b6c5b2034bc and make these changes in jupyter_spawner.py file.
tf-hub goes into CrashLoopBackOff error saying
IndentationError: unexpected indent

Can you suggest some solution to this to add persistent volume ?

### PR DESCRIPTION
**Pull request by inc0**
Besides adding chown /home/$USER also move non-install layers lower in
Dockerfile to make better use of docker cache during edits
Later we will probably switch to root user (issue #300), so it will make this whole section redundant.
Aslo touches #101 

Fixes #285

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/311)

### CODE REVIEW

**Comment by inc0** [comment]
note @jlewi - we'll need to re-push images to hub after it merges

File: components/tensorflow-notebook-image/start.sh [hunk 1]
```diff
@@ -24,14 +24,11 @@ if [ $(id -u) == 0 ] ; then
...
-        # container is started. Use the $NB_USER home path explicitly.
-        for d in "$CONDA_DIR" "$JULIA_PKGDIR" "/home/$NB_USER"; do
-            if [[ ! -z "$d" && -d "$d" ]]; then
-                echo "Set ownership to uid $NB_UID: $d"
-                chown -R $NB_UID "$d"
-            fi
-        done
+    fi
+
+    # Ensure pv directory belongs to user
```
Comment (jlewi) [inline components/tensorflow-notebook-image/start.sh]: Why are you no longer changing the ownership of the CONDA_DIR and JULIA_PKG_DIR.

Can you explain what the new code does differently? It looks like the only difference is that instead of doing chown with the UID we use the username now.

Do you know why that makes a difference?

Comment (inc0) [reply components/tensorflow-notebook-image/start.sh]: Difference is that, instead of changing only CONDA_DIR and JULIA_PKG_DIR (both of which lives in /home/$NB_USER) we chown whole /home/$NB_USER - most importantly /home/$NB_USER/work

Because we change user here in the script (line 48) and not in kubernetes manifest, PV isn't connected with correct user ownership, it assumes root (if you look at our notebook pod manifesto, it explicitly runs container as UID 0). I'm doing chown in startup script instead.

Comment (jlewi) [reply components/tensorflow-notebook-image/start.sh]: Do you know why run the container as UID 0? Should we not be doing that?

The original code was 

```
for d in "$CONDA_DIR" "$JULIA_PKGDIR" "/home/$NB_USER"; do
```

So it chown'd the whole /home/$NB_USER dir.

It looks like the difference is that you are now doing this always as opposed to

```
if [ "$NB_UID" != $(id -u $NB_USER) ]
```
What I'm inferring from this is that NB_UID = id NB_USER therefore in the current startup script we are not executing the chown. 

However, for some reason the permsions on /home/${NB_USER} are not set correctly to allow that user to use that container.

If UID is 0, doesn't that mean we are running as root?

Comment (inc0) [reply components/tensorflow-notebook-image/start.sh]: Ah you're right, I'll restore CONDA_DIR etc, issue was "if" above.

I think we shouldn't run it as root, maybe ensure perms for these dirs in Dockerfile. I'll open separate issue for that one tho as someone did that on purpose:)

Yeah we run pod as root, but start.sh does su $NB_USER <<command>> so we run jupyter itself as NB_USER. Not a typical way to deal with it tbh.

**Comment by inc0** [comment]
If we run as root ( #300 ) this issue wouldn't happen too

**Comment by inc0** [comment]
Done, I linked #101 which has slack link in discussion

**Comment by jlewi** [comment]
/assign @willb 

Adding Will because apparently running as root causes problems for open shift.

**Comment by jlewi** [comment]
@inc0 clued me in

- The pod is already running with `runAsUser:0`
    Here's a [gist](https://gist.github.com/jlewi/457e80e153725bf91f7f6d4eb60a65b2) for a pod showing it to be true

- We can't  figure out where this is being set; it doesn't appear to be in our config and we didn't see it in [KubeSpawner](https://github.com/jupyterhub/kubespawner/blob/f3a263791423ecbc84f802ec065183dd1efa23f4/kubespawner/objects.py#L79)

- Nothing in this PR is changing how we run as root so it shouldn't have any impact on OpenShift (its possible things are already broken on OpenShift)

- All this PR does is chown the /home/$NB_USER  but this is only done if the user is root (its guarded by an if) so it shouldn't have any impact in the case where we don't run as root.

- If we set the uid/gid of the pod correctly then we think K8s will automatically set the permissions on the PV.

- So this PR fixes a bug with PVC not working and shouldn't have any other impact. So I'm merging it.
