### PR TITLE
fix(admission-webhook): attach namespace to pod request if pod does not have it

### LINKED ISSUE #6027: PodDefault doesn't apply to Pods generated from Deployment
/kind bug

**What steps did you take and what happened:**
I defined a simple PodDefault that should inject a simple environnement variable:
```
apiVersion: "kubeflow.org/v1alpha1"
kind: PodDefault
metadata:
  name: add-env
spec:
 selector:
  matchLabels:
    my-add-env: 'true'
 env:
 - name: "var"
   value: "my-value"
```

When I deploy a pod directly such as this one:
```
apiVersion: v1
kind: Pod
metadata:
  name: my-direct-pod
  labels:
    app: nginx
    my-add-env: 'true'
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
``` 
and the PodDefault is applied correctly

but if I deploy a Pod by using a Deployment object as this one:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    my-add-env: 'true'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        my-add-env: 'true'
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```
the PodDefault is not applied, whereas the label that should trigger the PodDefault clearly exist in the Pod that is created by the deployement.

**What did you expect to happen:**
The PodDefault should be applied to the pod created by the deployement.

**Environment:**

- Kubeflow version: 1.2 and 1.3
- Kubernetes platform: on-prem kubernetes 
- Kubernetes version: 
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-r0-CCE20.8.1.3.B001-17.36.5", GitCommit:"d61c11191a704802f93e5d86877a8fcffe208d58", GitTreeState:"clean", BuildDate:"2020-10-16T09:38:58Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

### PR DESCRIPTION
**Pull request by henrysecond1**
Fixes #6027

When pod is deployed via `Deployment` object, namespace can be missing on `Pod` object in admission review request.

In this case, `PodDefault` can not be attached to pods since they do not have a namespace, 
and filtered by `filterPodDefaults` like below.
- https://github.com/kubeflow/kubeflow/blob/66bf469afdc1fc6bfc887c8c823234cc2b70a5d6/components/admission-webhook/main.go#L84

Since admission review request itself contains a namespace field, we can avoid problem above by attaching namespace to pod request if pod does not have it. I verified that `PodDefault` works correctly on deploying pod via `Deployment` object.

Also I just ran `go mod tidy` for cleaning unused dependencies.

Please take a look, thanks.

### CODE REVIEW

**Comment by ekesken** [comment]
I was about to send a similar PR for this problem, and saw that one which is not approved since July 17.

@elikatsis @kimwnasptd @Bobgy @pdmack can you have a look?

This is the proper solution for this auto-closed issue as well: https://github.com/kubeflow/kubeflow/issues/5149

And it's a serious blocker for us, we try to inject `pip.conf` files using PodDefault, but since we create our notebooks via deployments it's not possible to use it at all.

File: components/admission-webhook/main.go [hunk 1]
```diff
@@ -82,7 +82,7 @@ func filterPodDefaults(list []settingsapi.PodDefault, pod *corev1.Pod) ([]*setti
 		}
 		// check if the pod namespace match the poddefault's namespace
 		if pd.GetNamespace() != pod.GetNamespace() {
-			klog.Infof("PodDefault '%s' is not in the namespcae of pod '%s' ", pd.GetName(), pod.GetName())
+			klog.Infof("PodDefault '%s' is not in the namespace of pod '%s' ", pd.GetName(), pod.GetName())
```
Comment (ekesken) [inline components/admission-webhook/main.go:85]:
```suggestion
			klog.Infof("PodDefault '%s/%s' is not in the namespace of pod '%s/%s'", pd.GetNamespace(), pd.GetName(), pod.GetNamespace(), pod.GetName())
```

File: components/admission-webhook/main.go [hunk 2]
```diff
@@ -463,6 +463,10 @@ func mutatePods(ar v1beta1.AdmissionReview) *v1beta1.AdmissionResponse {
 	}
 	reviewResponse := v1beta1.AdmissionResponse{}
 	reviewResponse.Allowed = true
+	if pod.Namespace == "" {
+		pod.Namespace = ar.Request.Namespace
+	}
```
Comment (ekesken) [inline components/admission-webhook/main.go:468]:
```suggestion
	if pod.Namespace == "" {
		klog.Infof("Namespace was not set explicitly in Pod manifest, falling back to the namespace-'%s' coming from AdmissionReview request", ar.Request.Namespace)	
		pod.Namespace = ar.Request.Namespace
	}
```

**Comment by kimwnasptd** [comment]
@ekesken both your review suggestions make sense. I'll wait a little bit if @henrysecond1 commits them. If not I'll just commit your proposed changes and merge the PR, to include it in the 1.4 release.

File: components/admission-webhook/main.go (hunk 1 above)
Comment (henrysecond1) [reply components/admission-webhook/main.go:85]: Thanks for the suggestion!

File: components/admission-webhook/main.go (hunk 2 above)
Comment (henrysecond1) [reply components/admission-webhook/main.go:468]: Thanks for the suggestion!

**Comment by henrysecond1** [comment]
@ekesken @kimwnasptd  Thanks for checking it and the suggestion. I committed them

**Comment by kimwnasptd** [comment]
@henrysecond1 thanks for the prompt reply!

/lgtm
/approve
