### PR TITLE
Fix #5111: Trim whitespace from custom images

### LINKED ISSUE #5111: Trim whitespace around notebook images to avoid pod creation failure
/kind bug

**What steps did you take and what happened:**
When using a custom notebook image that's copy-pasted from somewhere, it frequently happens that whitespace on either end is included. This means the notebook server fails to start:

```
create Pod latest-0 in StatefulSet latest failed error: Pod "latest-0" is invalid: spec.containers[0].image: Invalid value: "some-custom-image-1.0.0 ": must not have leading or trailing whitespace
```

For beginners, this is troublesome, as they have to look through Kubernetes events to figure out what went wrong. A better error message would be one way to solve it, but probably easiest is if whitespace is automatically trimmed from either end.

**What did you expect to happen:**
Notebook server started correctly.

**Environment:**

- Kubeflow version: 1.0.0
- Kubernetes version: 1.15

### PR DESCRIPTION
**Pull request by ianhellstrom**
See: #5111 

It trims the whitespace around custom images to avoid pod creation failures. It does so in the backend and Rok template, where `customImage` is explicitly set.

---

Note: I tried running both the frontend and backend on my own machine but could not make it work. Perhaps the instructions for npm and Flask are outdated. I ran Flask in a fresh virtual environment.

NPM:

```
../src/create_string.cpp:17:25: error: no matching constructor for initialization of 'v8::String::Utf8Value'
  v8::String::Utf8Value string(value);
                        ^      ~~~~~
```

Flask:

```
2020-07-07 13:43:47,944 | kubeflow_jupyter.default.app | INFO | Sending file 'index.html'
127.0.0.1 - - [07/Jul/2020 13:43:47] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/ian/Python/backend/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ian/Python/backend/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ian/Code/oss/kubeflow/components/jupyter-web-app/backend/kubeflow_jupyter/default/app.py", line 77, in serve_root
    return send_from_directory("./static/", "index.html")
  File "/Users/ian/Python/backend/lib/python3.7/site-packages/flask/helpers.py", line 709, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

### CODE REVIEW

**Comment by ianhellstrom** [comment]
@googlebot I consent.

File: components/jupyter-web-app/frontend/src/app/uis/rok/rok-resource-form/rok-jupyter-lab-selector/rok-jupyter-lab-selector.component.ts [hunk 1]
```diff
@@ -47,7 +47,7 @@ export class RokJupyterLabSelectorComponent implements OnInit {
   }
 
   setLabValues(lab: JupyterLab) {
-    this.parentForm.get("customImage").setValue(lab.image);
+    this.parentForm.get("customImage").setValue(lab.image.trim());
```
Comment (kimwnasptd) [inline components/jupyter-web-app/frontend/src/app/uis/rok/rok-resource-form/rok-jupyter-lab-selector/rok-jupyter-lab-selector.component.ts:50]: I think you meant to use the `.strip()` function here right?

Comment (ianhellstrom) [reply components/jupyter-web-app/frontend/src/app/uis/rok/rok-resource-form/rok-jupyter-lab-selector/rok-jupyter-lab-selector.component.ts:50]: I don't think [so](https://www.w3schools.com/jsref/jsref_trim_string.asp), but I may be wrong.

Comment (kimwnasptd) [reply components/jupyter-web-app/frontend/src/app/uis/rok/rok-resource-form/rok-jupyter-lab-selector/rok-jupyter-lab-selector.component.ts:50]: @ianhellstrom my bad, I got confused for a second and thought this was also python code

**Comment by kimwnasptd** [comment]
@ianhellstrom the changes look good, thanks for the PR!

/lgtm
/approve
