### PR TITLE
Fixed Dashboard v0.0.1 w/ Polymer3 + Webpack

### LINKED ISSUE #2582: Central dashboard doesn't render; lots of 404s
I just deployed from master: commit: v0.4.0-rc.1-173-g3ea53cc2

central dashboard is using image gcr.io/kubeflow-images-public/centraldashboard:v20190223-v0.4.0-rc.1-152-g1de09b7a

The central dashboard returns lots of 404s; e.g. 

```
Request URL: http://localhost:8080/bower_components/webcomponentsjs/webcomponents-loader.js
Request Method: GET
Status Code: 404 Not Found
Remote Address: [::1]:8080
Referrer Policy: no-referrer-when-downgrade
Content-Length: 19
Content-Type: text/plain; charset=utf-8
Date: Thu, 28 Feb 2019 21:44:56 GMT
X-Content-Type-Options: nosniff
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Cookie: grafana_sess=966a5e96be9fe5ca; username-localhost-8888="2|1:0|10:1551052659|23:username-localhost-8888|44:Y2QxYWZlMTQ5NTBiNDYzMmJkODMxNDI0YWViZDBkMDk=|0f74ad55be44f4423db404ea3caa7c25def927e7b83451481bcba055e926cba5"; _xsrf=2|4c7b12ff|c4c1e9217e46a4da7c01ef53b10c91fe|1551052659
Host: localhost:8080
Referer: http://localhost:8080/
```

### PR DESCRIPTION
**Pull request by avdaredevil**
#### fixes #2582

- Fixed webpack for windows (components/ is not a valid path in windows)
- Spacing and semicolons matched to old-codebase
- Added cross-platform support to npm run targets
- Added missing dep (babel/polyfill)
- Dashboard build version is now corrected and hover will reveal kubeflow vs Dashboard versions
- Pug fixed to match syntax for empty-value attributes
- Updated webpack for readability

/assign @avdaredevil 
/assign @prodonjs 

/cc @jlewi

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2576)

### CODE REVIEW

**Comment by avdaredevil** [comment]
This version also fixes broken dashboard image in production

/assign @zhenghuiwang 
/cuj landing-page
/area centraldashboard

File: components/centraldashboard/public/components/main-page.js [hunk 1]
```diff
@@ -1,79 +1,78 @@
-import { PolymerElement, html } from '@polymer/polymer/polymer-element.js';
+import {PolymerElement, html} from '@polymer/polymer/polymer-element.js'
```
Comment (prodonjs) [inline components/centraldashboard/public/components/main-page.js]: I feel pretty strongly that this is not something we should change. We should follow a commonly accepted standard and in this case I think it makes sense to choose the [Google JS Style guide](https://google.github.io/styleguide/jsguide.html#formatting-semicolons-are-required) which explicitly requires semi-colons.

There's an [eslint](https://github.com/google/eslint-config-google) configuration we can add to enforce this.

File: components/centraldashboard/webpack.config.js [hunk 2]
```diff
@@ -1,20 +1,20 @@
...
+const ScriptExtHtmlWebpackPlugin = require('script-ext-html-webpack-plugin')
 
-const NODE_MODULES = /\/node_modules\//;
-const ENV = process.env.NODE_ENV || 'development';
-const PKG_VERSION = require('./package.json').version;
-const SRC = resolve(__dirname, 'public');
-const COMPONENTS = resolve(SRC, 'components');
-const DESTINATION = resolve(__dirname, 'dist', 'public');
-const WEBCOMPONENTS = './node_modules/@webcomponents/webcomponentsjs';
+const ENV           = process.env.NODE_ENV || 'development'
```
Comment (prodonjs) [inline components/centraldashboard/webpack.config.js]: This would be discouraged by the Google style guide.

https://google.github.io/styleguide/jsguide.html#formatting-horizontal-alignment

File: components/centraldashboard/package.json [hunk 3]
```diff
@@ -28,6 +28,7 @@
   },
   "homepage": "https://github.com/kubeflow/kubeflow#readme",
   "dependencies": {
+    "@babel/polyfill": "^7.2.5",
```
[the remark this answers is not in the document]
Comment (prodonjs) [reply components/centraldashboard/package.json]: Nevermind. I think I overestimated the scope of the webcomponents polyfills as also including standard polyfills for ES6. I do think we still need to import `@babel/polyfill` in our entry point.

I've added that to my PR #2579. Feel free to merge the applicable changes from that into this change, or if you want to approve, we can merge that into master first and then your change will only be to fix the Windows specific stuff.

[the remark this answers is not in the document]
Comment (avdaredevil) [reply components/centraldashboard/package.json]: Yeah, let's merge yours, since it addresses a bug, and then this can be a feature merge.

File: components/centraldashboard/public/components/main-page.js (hunk 1 above)
Comment (yebrahim) [reply components/centraldashboard/public/components/main-page.js]: Big plus one here.

File: components/centraldashboard/webpack.config.js [hunk 4]
```diff
@@ -81,19 +81,19 @@ module.exports = {
...
-                use: {
-                    loader: 'eslint-loader',
-                    options: {
-                        extends: ['eslint:recommended', 'google'],
-                        failOnError: true,
-                        fix: true
-                    }
-                }
-            },
+            // {
```
Comment (prodonjs) [inline components/centraldashboard/webpack.config.js]: I'm not sure why this would fail. It builds properly in the Docker container so that seems to indicate that it might be something unique to your machine. What kind of errors are you seeing?

File: components/centraldashboard/package.json [hunk 5]
```diff
@@ -61,6 +61,7 @@
     "clean-webpack-plugin": "^1.0.1",
     "concurrently": "^4.1.0",
     "copy-webpack-plugin": "^5.0.0",
+    "cross-env": "^5.2.0",
```
Comment (prodonjs) [inline components/centraldashboard/package.json]: I also noticed that the terser-webpack-plugin got added to deps instead of devDeps. Can you move that in this commit?

File: components/centraldashboard/webpack.config.js [hunk 6]
```diff
@@ -9,13 +9,13 @@ const MiniCssExtractPlugin = require("mini-css-extract-plugin");
...
-const SRC = resolve(__dirname, 'public');
-const COMPONENTS = resolve(SRC, 'components');
-const DESTINATION = resolve(__dirname, 'dist', 'public');
-const WEBCOMPONENTS = './node_modules/@webcomponents/webcomponentsjs';
+const NODE_MODULES = /\/node_modules\//;
+const PKG_VERSION = require('./package.json').version
+const SRC = resolve(__dirname, 'public')
+const COMPONENTS = resolve(SRC, 'components')
+const DESTINATION = resolve(__dirname, 'dist', 'public')
+const WEBCOMPONENTS = './node_modules/@webcomponents/webcomponentsjs'
```
[the remark this answers is not in the document]
Comment (avdaredevil) [reply components/centraldashboard/webpack.config.js]: Right, windows understands `/` paths even without the `resolve`

The issue last time was that node was fetching a path which returns in `\` but the regex only supported `/` path delims

File: components/centraldashboard/webpack.config.js (hunk 4 above)
Comment (avdaredevil) [reply components/centraldashboard/webpack.config.js]: > Missing eslint configuration

File: components/centraldashboard/package.json (hunk 5 above)
Comment (avdaredevil) [reply components/centraldashboard/package.json]: Sure

File: components/centraldashboard/webpack.config.js (hunk 4 above)
Comment (prodonjs) [reply components/centraldashboard/webpack.config.js]: Hmm and that's still the case after deleting `node_modules/` and doing a clean `npm install`? The required configs should be in devDependencies.

```
    "eslint": "^5.14.1",
    "eslint-config-google": "^0.12.0",
    "eslint-loader": "^2.1.2",
```

Comment (avdaredevil) [reply components/centraldashboard/webpack.config.js]: This is the error was:
```
ERROR in (webpack)-dev-server/client?http://localhost:8081
[Webpack] Module build failed (from <redacted>/Google/Kubeflow/kubeflow/components/centraldashboard/node_modules/eslint-loader/index.js):
[Webpack] Error: No ESLint configuration found.
[Webpack]     at Config.getLocalConfigHierarchy (<redacted>\Google\Kubeflow\kubeflow\components\centraldashboard\node_modules\eslint\lib\config.js:268:39)
[Webpack]     at Config.getConfigHierarchy (<redacted>\Google\Kubeflow\kubeflow\components\centraldashboard\node_modules\eslint\lib\config.js:192:43)
[Webpack]     at Config.getConfigVector (<redacted>\Google\Kubeflow\kubeflow\components\centraldashboard\node_modules\eslint\lib\config.js:299:21)
[Webpack]     at Config.getConfig (<redacted>\Google\Kubeflow\kubeflow\components\centraldashboard\node_modules\eslint\lib\config.js:342:29)
[Webpack]     at processText (<redacted>\Google\Kubeflow\kubeflow\components\centraldashboard\node_modules\eslint\lib\cli-engine.js:181:33)
[Webpack]     at CLIEngine.executeOnText (<redacted>\Google\Kubeflow\kubeflow\components\centraldashboard\node_modules\eslint\lib\cli-engine.js:690:40)
[Webpack]     at lint (<redacted>\Google\Kubeflow\kubeflow\components\centraldashboard\node_modules\eslint-loader\index.js:263:17)
[Webpack]     at Object.module.exports (<redacted>\Google\Kubeflow\kubeflow\components\centraldashboard\node_modules\eslint-loader\index.js:258:21)
[Webpack]  @ multi (webpack)-dev-server/client?http://localhost:8081 <redacted>/Google/Kubeflow/kubeflow/components/centraldashboard/public/index.js main[0]
```

File: components/centraldashboard/webpack.config.js [hunk 7]
```diff
@@ -27,13 +27,13 @@ const POLYFILLS = [
         to: resolve(DESTINATION, 'webcomponentsjs', 'bundles'),
         flatten: true
     }
-];
+]
```
Comment (prodonjs) [inline components/centraldashboard/webpack.config.js]: Please add the semi-colon back in accordance with the Google JS style.

File: components/centraldashboard/webpack.config.js (hunk 4 above)
Comment (prodonjs) [reply components/centraldashboard/webpack.config.js]: As discussed, this seems like a Windows-platform specific issue since the build succeeds on Linux and within Docker during its build process. Please leave the eslint-loader section in place.

File: kubeflow/common/prototypes/centraldashboard.jsonnet [hunk 8]
```diff
@@ -3,7 +3,7 @@
 // @description centraldashboard Component
 // @shortDescription centraldashboard
 // @param name string Name
-// @optionalParam image string gcr.io/kubeflow-images-public/centraldashboard:v20190223-v0.4.0-rc.1-152-g1de09b7a Image for the central dashboard
+// @optionalParam image string gcr.io/kubeflow-images-public/centraldashboard:v20190301-v0.4.0-rc.1-183-g07eecd2f Image for the central dashboard
```
Comment (prodonjs) [inline kubeflow/common/prototypes/centraldashboard.jsonnet]: Just a question, does this comment need to be updated with every subsequent release? Wouldn't a user typically just want to deploy the **gcr.io/kubeflow-images-public/centraldashboard:latest** or search for their specific tag during development?

Comment (avdaredevil) [reply kubeflow/common/prototypes/centraldashboard.jsonnet]: So we definitely don't like pushing to `:latest`, though there is a make recipe for it (@jlewi can possibly elaborate on why that is). But no we don't generally make an update everytime. But because the last 2 images were broken (bower deps were missing, and wrong port was being used). This release fixes both those issues.

**Comment by jlewi** [comment]
/lgtm
/approve

@prodonjs We need to get you added to the org before your LGTM will take effect.

/hold

@prodonjs Are you still waiting for the latest comments to be addressed?

**Comment by prodonjs** [comment]
@jlewi I am good with AP's latest changes. I thought I had been added to the org last week when my [PR](https://github.com/kubeflow/internal-acls/pull/63) to internal-acls was approved. I guess I didn't receive the invite yet as indicated in https://www.kubeflow.org/docs/about/contributing/#joining-the-kubeflow-github-org.
