### PR TITLE
Apply refactor

### LINKED ISSUE #3810: Running kfctl apply k8s fails on 2nd application
/kind bug

**What steps did you take and what happened:**
I ran `kfctl apply k8s` a 2nd time and it failed saying istio had already bound the port.

output:

> time="2019-08-01T14:24:56-07:00" level=info msg="creating Service/istio-galley\n" filename="kustomize/kustomize.go:440"
> time="2019-08-01T14:24:56-07:00" level=info msg="creating Service/istio-ingressgateway\n" filename="kustomize/kustomize.go:440"
> Error: couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: couldn't create resources from istio-install Error: Service "istio-ingressgateway" is invalid: spec.ports[1].nodePort: Invalid value: 31380: provided port is already allocated
> Usage:
>   kfctl apply [all(=default)|k8s|platform] [flags]
> 
> Flags:
>   -h, --help      help for apply
>   -V, --verbose   verbose output default is false
> 
> couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: couldn't create resources from istio-install Error: Service "istio-ingressgateway" is invalid: spec.ports[1].nodePort: Invalid value: 31380: provided port is already allocated
> 

**What did you expect to happen:**

Since the docs https://www.kubeflow.org/docs/gke/customizing-gke/ suggest that I can reapply, I expected this to silently skip istio or otherwise not fail. 

**Anything else you would like to add:**
Short term solution could be a doc change, longer term I think we do want to support kfctl apply k8s multiple times.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): master (df2b68d92cf15374b1706d3d91b8123972b8920c)
- kfctl version: (use `kfctl version`): v20181207-4e7f4ed-198-gaeea303e-dirty-03e65e
- Kubernetes platform: (e.g. `minikube`) gke
- Kubernetes version: (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.9-gke.7", GitCommit:"b6001a5d99c235723fc19342d347eee4394f2005", GitTreeState:"clean", BuildDate:"2019-06-18T12:12:30Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

### PR DESCRIPTION
**Pull request by kkasravi**
initial checkin

fixes #3810 

- [x] `kfctl apply` didn't rate limit 
- [x] `kfctl apply` didn't wait for resource creation 
- [x] `kfctl apply` didn't do a strategic merge on existing resources

kfctl now invokes the same method kubectl does which addresses the above problems

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3957)

### CODE REVIEW

File: bootstrap/pkg/kfapp/kustomize/kustomize.go [hunk 1]
```diff
@@ -250,15 +252,115 @@ func (kustomize *kustomize) initK8sClients() error {
...
+	if err := tmpfile.Close(); err != nil {
+		log.Fatal(err)
+	}
+	return os.Remove(tmpfile.Name())
+}
+
 // Apply deploys kustomize generated resources to the kubenetes api server
 func (kustomize *kustomize) Apply(resources kftypesv3.ResourceEnum) error {
-	if err := kustomize.initK8sClients(); err != nil {
+	os.Setenv(envBackoffBase, "1")
```
Comment (jlewi) [inline bootstrap/pkg/kfapp/kustomize/kustomize.go]: Why are we setting these environment variables? Doesn't this prevent users from customizing the behavior by setting these environment variables?

**Comment by jlewi** [comment]
Looks good other than the test failures

/assign @jlewi

File: bootstrap/pkg/kfapp/kustomize/kustomize.go (hunk 1 above)
Comment (kkasravi) [reply bootstrap/pkg/kfapp/kustomize/kustomize.go]: yes, you're right. I don't think I need them. The 'magic' setting is ShouldIncludeUninitialized=false which means wait for creation for new objects

**Comment by jlewi** [comment]
Should we update the E2E tests to run apply a 2nd time so we can verify its fixed?

**Comment by yanniszark** [comment]
Hi @kkasravi, I took another look at the latest code.
Is it necessary to have separate Init, Run, Cleanup functions?
Why not wrap everything inside a single function (eg an Apply function) and call that?

I was also thinking:
* Why do we need an interface instead of just calling methods?
* The namespace-related functions don't look like they belong as methods in an apply wrapper struct. How about calling the Apply function with the namespace object from the kustomize code?

**Comment by jlewi** [comment]
I don't think I have anything to add to @yanniszark 's review.

**Comment by kkasravi** [comment]
@jlewi @yanniszark I've updated the code to accommodate the suggestions.

**Comment by jlewi** [comment]
lgtm on my end

File: bootstrap/pkg/utils/k8utils.go [hunk 2]
```diff
@@ -325,3 +146,198 @@ func DeleteResourceFromFile(config *rest.Config, filename string) error {
...
+	}
+	apply.clientset = clientset
+	err = apply.namespace(kfDef)
+	if err != nil {
+		return nil, err
+	}
+	return apply, nil
+}
+
+func (a *Apply) DefaultProfileNamespace(name string) bool {
```
Comment (yanniszark) [inline bootstrap/pkg/utils/k8utils.go]: It seems weird to have a `DefaultProfileNamespace` method for an apply helper struct.
I feel like this is something that should happen inside the kustomize.go file.
How about exposing a `GetClientset` function, so that we can just get a K8s clientset and use it with our client of choice (client-go, controller-runtime).

File: bootstrap/pkg/kfapp/kustomize/kustomize.go [hunk 3]
```diff
@@ -286,189 +259,73 @@ func (kustomize *kustomize) Apply(resources kftypesv3.ResourceEnum) error {
...
-					continue
-				default:
-					return result.Error()
+			b := backoff.NewExponentialBackOff()
+			b.InitialInterval = 3 * time.Second
+			b.MaxInterval = 30 * time.Second
+			b.MaxElapsedTime = 5 * time.Minute
+			return backoff.Retry(func() error {
+				if !apply.DefaultProfileNamespace(defaultProfileNamespace) {
+					msg := fmt.Sprintf("Could not find namespace %v, wait and retry", defaultProfileNamespace)
```
Comment (swiftdiaries) [inline bootstrap/pkg/kfapp/kustomize/kustomize.go]: Can we create a namespace if one doesn't exist?

File: bootstrap/pkg/kfapp/kustomize/kustomize.go [hunk 4]
```diff
@@ -286,189 +259,73 @@ func (kustomize *kustomize) Apply(resources kftypesv3.ResourceEnum) error {
...
 		}
-		resourcesErr := kustomize.deployResources(kustomize.restConfig, data)
-		if resourcesErr != nil {
-			return &kfapisv3.KfError{
-				Code:    int(kfapisv3.INTERNAL_ERROR),
-				Message: fmt.Sprintf("couldn't create resources from %v Error: %v", app.Name, resourcesErr),
-			}
+		err = apply.Apply(data)
+		if err != nil {
+			return err
```
Comment (kunmingg) [inline bootstrap/pkg/kfapp/kustomize/kustomize.go]: Currently when error occurs, we stop for loop and return error.
Can we instead 
1. still finish the for loop while pile up errors
2. return `[]error` when `apply` finished?

I feel 1 or 2 failed resource shouldn't block applying the rest?

Comment (kkasravi) [reply bootstrap/pkg/kfapp/kustomize/kustomize.go]: Hi @kunmingg 

kubectl's apply.run will aggregate errors and continue with best effort.
I added cmdutil.checkErr(resourcesErr) if resourcesErr != nil.
CheckErr will print out multiple errors if it has aggregated more than one.

**Comment by kunmingg** [comment]
/lgtm
Thanks!

File: bootstrap/pkg/utils/k8utils.go [hunk 5]
```diff
@@ -325,3 +145,198 @@ func DeleteResourceFromFile(config *rest.Config, filename string) error {
 	}
 	return nil
 }
+
+type Apply struct {
```
Comment (nrchakradhar) [inline bootstrap/pkg/utils/k8utils.go]: Just a thought. Found it very confusing to have name "Apply".Can this be renamed to Applykubectl or KubectlApply? There are too many "apply"s now in kfctl so was thinking that renaming will help.

Comment (yanniszark) [reply bootstrap/pkg/utils/k8utils.go]: How about ApplyResources, similar to CreateResources and DeleteResources that we have now?

**Comment by nrchakradhar** [comment]
> > _[Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3957)_ status: 0 of 4 files reviewed, 8 unresolved discussions (waiting on @jlewi, @kunming, @nrchakradhar, @richardsliu, and @yanniszark)
> 
> _[bootstrap/pkg/utils/k8utils.go, line 149 at r6](https://reviewable.io/reviews/kubeflow/kubeflow/3957#-Lmpg2Fzp1y2e2Y6x1h8-r6-149:-Lnph7H_Cqh5KeQCY4Ja:bu41gbj) ([raw file](https://github.com/kubeflow/kubeflow/blob/9beb669330895cabc45e8e9d81b597463c34cdd9/bootstrap/pkg/utils/k8utils.go#L149)):_
> 
> Previously, yanniszark (Yannis Zarkadas) wrote…
> This is a bikeshedding issue and can be done in a follow-up PR.

@kkasravi 
Its fine for a follow-up PR.

**Comment by kunmingg** [comment]
@kkasravi 
Tests are failing, you might need to rebase after https://github.com/kubeflow/kubeflow/pull/4053 merged.
