### PR TITLE
Bug fix for #1559

### LINKED ISSUE #1559: "Patching IAM bindings" halt during deployment.
log tail:

{"filename":"app/ksServer.go:805","level":"info","msg":"Deployment is done","time":"2018-09-18T23:36:34Z"}
{"filename":"app/ksServer.go:817","level":"info","msg":"Patching IAM bindings...","time":"2018-09-18T23:36:34Z"}

### PR DESCRIPTION
**Pull request by lluunn**
fix #1559 

/cc @kunmingg

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1561)

### CODE REVIEW

File: bootstrap/cmd/bootstrap/app/gcpUtils.go [hunk 1]
```diff
@@ -202,6 +202,7 @@ func (s *ksServer)ApplyIamPolicy(ctx context.Context, req ApplyIamRequest) error
 			log.Warningf("Cannot set new ploicy: %v", err)
```
Comment (kunmingg) [inline bootstrap/cmd/bootstrap/app/gcpUtils.go]: Will still break even an error occurs

Comment (lluunn) [reply bootstrap/cmd/bootstrap/app/gcpUtils.go]: thanks, fixed
