### PR TITLE
List endpoints when delete is failed

### LINKED ISSUE #2900: kfctl e2e test failure: cannot delete endpoint
https://github.com/kubeflow/kubeflow/pull/2895#issuecomment-478806415

http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-presubmit-kfctl-go-iap-2895-4014fa2-1808-a964?tab=workflow&nodeId=kubeflow-presubmit-kfctl-go-iap-2895-4014fa2-1808-a964-785771799

cc @gabrielwen @kunmingg

### PR DESCRIPTION
**Pull request by gabrielwen**
Fixes #2900

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2912)

### CODE REVIEW

File: bootstrap/pkg/kfapp/gcp/gcp.go [hunk 1]
```diff
@@ -672,10 +672,37 @@ func (gcp *Gcp) deleteEndpoints(ctx context.Context) error {
...
+				return &kfapis.KfError{
+					Code:    int(kfapis.INTERNAL_ERROR),
+					Message: fmt.Sprintf("listing managed services error: %v", err),
+				}
+			}
+			for _, s := range listResp.Services {
+				if s.ServiceName == gcp.Spec.Hostname {
+					return &kfapis.KfError{
+						Code:    int(kfapis.INTERNAL_ERROR),
+						Message: fmt.Sprintf("issuing endpoint deletion error: %v", err),
```
Comment (lluunn) [inline bootstrap/pkg/kfapp/gcp/gcp.go]: this err is the error from list, should use the delete error?

File: bootstrap/pkg/kfapp/gcp/gcp.go [hunk 2]
```diff
@@ -672,10 +672,37 @@ func (gcp *Gcp) deleteEndpoints(ctx context.Context) error {
 	services := servicemanagement.NewServicesService(servicemanagementService)
 	op, err := services.Delete(gcp.Spec.Hostname).Context(ctx).Do()
 	if err != nil {
-		return &kfapis.KfError{
-			Code:    int(kfapis.INTERNAL_ERROR),
-			Message: fmt.Sprintf("issuing endpoint deletion error: %v", err),
+		nextPage := ""
+		for {
```
Comment (lluunn) [inline bootstrap/pkg/kfapp/gcp/gcp.go]: add a comment for this loop

File: bootstrap/pkg/kfapp/gcp/gcp.go (hunk 1 above)
Comment (gabrielwen) [reply bootstrap/pkg/kfapp/gcp/gcp.go]: this is because deletion is failed and we could still find endpoint service in the list - this is an actual deletion error.

File: bootstrap/pkg/kfapp/gcp/gcp.go (hunk 2 above)
Comment (gabrielwen) [reply bootstrap/pkg/kfapp/gcp/gcp.go]: added.

File: bootstrap/pkg/kfapp/gcp/gcp.go (hunk 1 above)
Comment (lluunn) [reply bootstrap/pkg/kfapp/gcp/gcp.go]: I mean, the err here is from list.Do.
shouldn't we return the err from services.Delete?

File: bootstrap/pkg/kfapp/gcp/gcp.go [hunk 3]
```diff
@@ -672,10 +672,38 @@ func (gcp *Gcp) deleteEndpoints(ctx context.Context) error {
...
+					}
+				}
+			}
+			// Explicitly copy it to prevent memory leak.
+			nextPage = "" + listResp.NextPageToken
+			if nextPage == "" {
+				break
+			}
 		}
+		// Delete is not successful and we are not able to find endpoint in managed
```
Comment (lluunn) [inline bootstrap/pkg/kfapp/gcp/gcp.go]: Do you know why this happens?
delete failed, but the endpoint is gone

Comment (kkasravi) [reply bootstrap/pkg/kfapp/gcp/gcp.go]: probably ksonnet deleted it and the platform couldn’t. I think we’ll have various race conditions - eg deleting the namespace and deleting things in the namespace.

File: bootstrap/pkg/kfapp/gcp/gcp.go (hunk 1 above)
Comment (gabrielwen) [reply bootstrap/pkg/kfapp/gcp/gcp.go]: changed.

File: bootstrap/pkg/kfapp/gcp/gcp.go (hunk 3 above)
Comment (gabrielwen) [reply bootstrap/pkg/kfapp/gcp/gcp.go]: yes, I think it's because ksonnet delete and gcp delete is trying to do overlapped tasks.

File: bootstrap/pkg/kfapp/gcp/gcp.go [hunk 4]
```diff
@@ -670,12 +670,40 @@ func (gcp *Gcp) deleteEndpoints(ctx context.Context) error {
 	}
 
 	services := servicemanagement.NewServicesService(servicemanagementService)
-	op, err := services.Delete(gcp.Spec.Hostname).Context(ctx).Do()
+	op, deleteErr := services.Delete(gcp.Spec.Hostname).Context(ctx).Do()
 	if err != nil {
```
Comment (lluunn) [inline bootstrap/pkg/kfapp/gcp/gcp.go]: should be deleteErr

Comment (gabrielwen) [reply bootstrap/pkg/kfapp/gcp/gcp.go]: good catch, thanks!
