### PR TITLE
Improvements and bug fixes in DM config.

### LINKED ISSUE #878: Deployment manager config should create service accounts and set IAM roles
Our deployment manager config should create service accounts and set IAM roles for those service accounts appropriately.

We should create two service accounts

1. For admin tasks like enabling endpoints 
1. For use with TFJobs etc...
   * Should have IAM roles like read/write to various storage products
   * Dataflow access; etc...

### PR DESCRIPTION
**Pull request by jlewi**
* Create a service account to be used to authorize TFJobs and other work
  within the cluster.

* Create a helper script to download service account keys and turn
  them into K8s keys

* Fix some bugs in the docs.

* Fix #878 create a GCP service account for the user.

* IAP script needs a GCP service account with network admin privileges.
* Add network admin privileges to the admin service account.
* Name the secrets in K8s so that be default the names are the same across
  the deployments. This way there's one less parameter to set for
  every deployment.

* VM service account should have a unique name per deployment so deployments
  are isolated.

* Need to grant the VM service account logs and monitoring access to support
  monitoring.

* I don't think there's any reason to allow user to specify name of the
  VM service account in the YAML file right now.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/904)

### CODE REVIEW

File: docs/gke/create_k8s_secrets.sh [hunk 1]
```diff
@@ -0,0 +1,18 @@
+#!/bin/bash
+#
+# A simple helper script to download secrets for Kubeflow service
+# accounts and store them as K8s secrets.
+set -ex
+export SA_EMAIL=${DEPLOYMENT_NAME}-admin@${PROJECT}.iam.gserviceaccount.com
+
+# TODO(jlewi): We should name the secrets more consistently based on the service account name.
+# We will need to update the component configs though
+gcloud --project=${PROJECT} iam service-accounts keys create ${SA_EMAIL}.json --iam-account $SA_EMAIL
```
Comment (ankushagarwal) [inline docs/gke/create_k8s_secrets.sh]: nit: use ${SA_EMAIL}

File: docs/gke/configs/cluster.jinja [hunk 2]
```diff
@@ -286,9 +300,40 @@ TODO(jlewi): Do we need to serialize API activation
           members:
             - {{ 'serviceAccount:' + env['project_number'] + '@cloudservices.gserviceaccount.com' }}
 
+        {# servicemanagement.admin is needed by CloudEndpoints controller
```
Comment (ankushagarwal) [inline docs/gke/configs/cluster.jinja]: How do we manage deletion of IAM Role Bindings? When we delete the deployment, the service accounts go away but these IAM Role Bindings still lurk around.

Comment (jlewi) [reply docs/gke/configs/cluster.jinja]: Good point. Created 
https://github.com/kubeflow/kubeflow/issues/910
