### PR TITLE
Correct ContainerStatus of Notebook CR

### LINKED ISSUE #5282: Notebook controller is only checking the status of one (the first) container
/kind bug

**What steps did you take and what happened:**
When you add a new notebook server, the status of the newly added notebook becomes ready to soon. Namely, if you click on connect, a "no healthy upstream" message shows the first seconds. I tried to fix this by adding a readiness probe to the notebook container (via a custom admission controller). However, the problem stayed the same: the green check mark appears under status too soon.

**What did you expect to happen:**
Correct behavior of the status icon of the notebook server in the Kubeflow dashboard.

**Anything else you would like to add:**
I think I know what the problem is and why the status is wrongly reported in the Kubeflow dashboard: The notebook controller is only checking the status of the first container https://github.com/kubeflow/kubeflow/blob/c4717d84b6d927b7cf2305511002094e9d19f5a4/components/notebook-controller/controllers/notebook_controller.go#L210 

As a result, it's only taking the status of the istio-proxy container in consideration, and the status of the notebook container is ignored. I think this is a little bug, as the controller should definitely check the status of all containers, and not only the first one.

I'm new to this community, but if it's ok I would like to fix this and add a new pull request.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.0.2
- kfctl version: (use `kfctl version`): 1.0.2
- Kubernetes platform: (e.g. `minikube`): minikube
- Kubernetes version: (use `kubectl version`): client v1.19.0 , server v1.18.3
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

### PR DESCRIPTION
**Pull request by gilbeckers**
The Notebook Controller doesn't set the `ContainerState` of the CR correctly. In some cases the first container is the istio-sidecar which results in an incorrect state being shown to the Notebook CR. This is fixed now by showing the `ContainerState` of Notebook container to the Notebook CR `ContainerState`. 

The Notebook container is selected by matching with [the name of the notebook](https://github.com/kubeflow/kubeflow/blob/7f5e242f4671f453eaee72e4319a5f7f190f7725/components/jupyter-web-app/backend/kubeflow_jupyter/common/yaml/notebook.yaml#L14). A warning is logged in case no container is found.

This PR fixes #5282.

### CODE REVIEW

File: components/notebook-controller/controllers/notebook_controller.go [hunk 1]
```diff
@@ -206,23 +206,34 @@ func (r *NotebookReconciler) Reconcile(req ctrl.Request) (ctrl.Result, error) {
...
+					}
+					notebookContainerFound = true
+					break
+				}
 			}
-			err = r.Status().Update(ctx, instance)
-			if err != nil {
-				return ctrl.Result{}, err
+			if !notebookContainerFound {
+				log.Info("WARNING: Notebook container is not found, so could not update State of Notebook CR")
```
Comment (yanniszark) [inline components/notebook-controller/controllers/notebook_controller.go:236]: I don't think that a log.Info should emit a `WARNING` message.
If the message is indeed a warning, use `log.Warn`.
This sounds like an error though.

File: components/notebook-controller/controllers/notebook_controller.go [hunk 2]
```diff
@@ -206,23 +206,34 @@ func (r *NotebookReconciler) Reconcile(req ctrl.Request) (ctrl.Result, error) {
...
-			// Append new condition
-			if len(oldConditions) == 0 || oldConditions[0].Type != newCondition.Type ||
-				oldConditions[0].Reason != newCondition.Reason ||
-				oldConditions[0].Message != newCondition.Message {
-				log.Info("Appending to conditions: ", "namespace", instance.Namespace, "name", instance.Name, "type", newCondition.Type, "reason", newCondition.Reason, "message", newCondition.Message)
-				instance.Status.Conditions = append([]v1beta1.NotebookCondition{newCondition}, oldConditions...)
+
+		if len(pod.Status.ContainerStatuses) > 0 {
+			notebookContainerFound := false
+			for i := range pod.Status.ContainerStatuses {
```
Comment (kimwnasptd) [inline components/notebook-controller/controllers/notebook_controller.go:212]: Could you add a comment here to document that the status of the CR will be updated based on the `ContainerState` of the container that has the same name with the CR?

File: components/notebook-controller/controllers/notebook_controller.go (hunk 1 above)
Comment (kimwnasptd) [reply components/notebook-controller/controllers/notebook_controller.go:236]: I agree with @yanniszark.
Although AFAIK `logr` does not have a [Warning level](https://github.com/go-logr/logr#why-not-more-named-levels-like-warning). So we should do this an Error instead.

@gilbeckers could you also make the error message more explicit as to why it couldn't find the Notebook Container? Something like: `Could not find the Notebook container. No container has the same name with the CR '{container-name}'. Will not update the status of the CR.`

**Review by kimwnasptd — COMMENTED** [review]
@gilbeckers 
> This PR partially fixes #5282 (the fact that the status icon of newly created notebook server in the Kubeflow dashboard is not correct)

I think this PR fixes #5282 entirely since the issue was only about the notebooks controller. Could you open a new issue regarding the status icon of the newly created notebook server in the dashboard not being correct?

**Comment by gilbeckers** [comment]
> I think this PR fixes #5282 entirely since the issue was only about the notebooks controller. Could you open a new issue regarding the status icon of the newly created notebook server in the dashboard not being correct?

I updated my original comment

**Comment by kimwnasptd** [comment]
@gilbeckers apologies for the long delay. I would like to push this effort forward as it's something we want to fix for the next release.

Looking again at the code I have some more comments before merging this, mostly to simplify a little bit the code. @gilbeckers would you be interested in putting some small extra effort so we can merge this?

**Comment by gilbeckers** [comment]
@kimwnasptd I'm ok with putting some extra effort in this one. But can you please give some more info on what you have in mind, so that I can estimate what you mean with small effort.

File: components/notebook-controller/controllers/notebook_controller.go [hunk 3]
```diff
@@ -206,23 +206,37 @@ func (r *NotebookReconciler) Reconcile(req ctrl.Request) (ctrl.Result, error) {
...
-				log.Info("Appending to conditions: ", "namespace", instance.Namespace, "name", instance.Name, "type", newCondition.Type, "reason", newCondition.Reason, "message", newCondition.Message)
-				instance.Status.Conditions = append([]v1beta1.NotebookCondition{newCondition}, oldConditions...)
+
+		// Update status of the CR using the ContainerState of
+		// the container that has the same name as the CR.
+		// If no container of same name is found, the state of the CR is not updated.
+		if len(pod.Status.ContainerStatuses) > 0 {
+			notebookContainerFound := false
+			for i := range pod.Status.ContainerStatuses {
+				if pod.Status.ContainerStatuses[i].Name == instance.Name &&
```
Comment (kimwnasptd) [inline components/notebook-controller/controllers/notebook_controller.go:216]: Could you break this if statement to the following ones:

```golang
if pod.Status.ContainerStatuses[i].Name != instance.Name {
    continue
}

if pod.Status.ContainerStatuses[i].State == instance.Status.ContainerState {
    continue
}

log.Info("Updating Notebook CR state: ", "namespace", instance.Namespace, "name", instance.Name)
cs := pod.Status.ContainerStatuses[i].State
...
```

**Review by kimwnasptd — COMMENTED** [review]
It's just a small reorganization on some if statements to make the code a little bit more clear and not too much nested.

Ideally I think we should work on moving a lot of the logic of the `Reconcile` function into smaller functions. But this should be an independent effort on its own.

**Comment by gilbeckers** [comment]
@kimwnasptd I added your requested changes

**Comment by kimwnasptd** [comment]
The code looks good. Thanks for the contribution @gilbeckers!
/lgtm
/approve
