### PR TITLE
fixes 'bootstrap golang modules'

### LINKED ISSUE #2022: bootstrap golang modules
- Move from glide to go modules (golang 1.11.2)
- Define a multistage build docker file (move Dockerfile.build into Dockerfile) that uses the gomodule cache
- Remove unused script start.sh
- Upgrade debug.sh, dlv.sh to use go modules
- Upgrade kubectl to v1.12.2
- Upgrade ksonnet to v0.13.1

### PR DESCRIPTION
**Pull request by kkasravi**
fixes #2022

- [x] Move from glide to go modules (golang 1.11.2)
- [x] Define a multistage build docker file (move Dockerfile.build into Dockerfile) that uses the gomodule cache
- [x] Remove unused script start.sh
- [x] Upgrade debug.sh, dlv.sh to use go modules
- [x] Upgrade kubectl to v1.12.2
- [x] Upgrade ksonnet to v0.13.1

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2090)

### CODE REVIEW

**Comment by kkasravi** [comment]
@kunmingg, @jlewi - the [developer_guid.md](https://github.com/kubeflow/kubeflow/blob/24e759a70781c510d858c2b60ee18f912d0d0edf/bootstrap/developer_guide.md) has been updated as well.

File: bootstrap/Dockerfile [hunk 1]
```diff
@@ -1,16 +1,5 @@
...
-ARG BUILDER_IMG_VERSION=latest
-FROM ${BUILDER_IMG}:${BUILDER_IMG_VERSION} AS build_base_remote
-# Copy the src
-COPY ./ $GOPATH/src/github.com/kubeflow/kubeflow/bootstrap/
-
-RUN go build ${GOLANG_GCFLAGS} -i -o /opt/kubeflow/bootstrapper \
-    ${GOPATH}/src/github.com/kubeflow/kubeflow/bootstrap/cmd/bootstrap/main.go
-
-FROM golang:${GOLANG_VERSION} AS build
+ARG GOLANG_VERSION=1.11.2
```
Comment (jlewi) [inline bootstrap/Dockerfile]: @kunmingg Can we just delete this? Are we still using the boostrapper docker image for anything?
I think the web app has separate docker images?

**Comment by jlewi** [comment]
@kunmingg Are we still using the bootstrapper docker image?

**Comment by kkasravi** [comment]
@kunmingg does kubeflow/components/gcp-click-to-deploy/Dockerfile end up building kubeflow/bootstrap/cmd/bootstrap/main.go somehow?

**Comment by jlewi** [comment]
@kkasravi No I think bootstrap has its own Dockerfile and build process
https://github.com/kubeflow/kubeflow/tree/master/bootstrap

File: bootstrap/Dockerfile (hunk 1 above)
Comment (jlewi) [reply bootstrap/Dockerfile]: To answer my own question. The bootstrap container is what we are running for deploy.kubeflow.cloud

File: bootstrap/cleanup.sh [hunk 2]
```diff
@@ -0,0 +1,22 @@
+#!/usr/bin/env bash
```
Comment (jlewi) [inline bootstrap/cleanup.sh]: What is this script for?

**Comment by jlewi** [comment]
/lgtm
/hold

@kunmingg This looks good to me. Any additional comments?

File: bootstrap/cleanup.sh (hunk 2 above)
Comment (kkasravi) [reply bootstrap/cleanup.sh]: called in the Makefile

```
debug: push cleanup
        @echo debugging $(IMG):$(TAG) using port $(PORT)
        @./debug.sh $(IMG) $(TAG) $(PORT)
```

Calling `make debug` will build, push the image, cleanup from prior run as 
target dependencies - it will then call debug.sh

File: bootstrap/Dockerfile [hunk 3]
```diff
@@ -31,22 +20,38 @@ RUN wget -q https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.ta
...
+
+ENV PATH /go/bin:/usr/local/go/bin:$PATH
+# use go modules
+ENV GO111MODULE=on
+
+COPY go.mod .
+COPY go.sum .
+RUN go mod download
+
+FROM bootstrap_build as bootstrap
```
Comment (kunmingg) [inline bootstrap/Dockerfile]: Can we use golang:alpine here? and copy from bootstrap_build so we can have smaller output image?

Comment (kkasravi) [reply bootstrap/Dockerfile]: @kunmingg yes, great suggestion. 

I'll get this in tomorrow.

**Comment by kkasravi** [comment]
@kunmingg @jlewi size reduced from 1.2 GB -> 168 MB
Still able to run debug in the image (`make debug`)

**Comment by jlewi** [comment]
Woo Hoo
